set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
" git
Plugin 'tpope/vim-fugitive'
"代码生成器
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
"outline
Plugin 'majutsushi/tagbar'
"底部状态提示
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
"change somethings
Plugin 'tpope/vim-surround'
"filebrowser
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-commentary'
call vundle#end()            " required
filetype plugin indent on    " required
" 上面为Vundle管理内容
"
set encoding=utf-8
" our <leader> will be the space key
let mapleader=","
" 语法高亮，配色方案为solarized
syntax enable
set background=dark


" tab 替换为4个空格
set tabstop=4
set shiftwidth=4
set expandtab

"outline
"
nmap <F12> :TagbarToggle<CR>
let g:airline#extensions#tabline#enabled = 1

"netrw 配置
let g:netrw_banner = 0
let g:netrw_liststyle = 3

nmap <silent> <F9> <Plug>MarkdownPreview

" paste format
set pastetoggle=<F2>
set noswapfile

" search
" Highlight search results
set hlsearch
" Makes search act like search in modern browsers
set incsearch 
" clear highlight
nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>

